using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

public class move_player : MonoBehaviour
{

    [SerializeField] private Vector3 velocity;              // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½
    [SerializeField] private float moveSpeed = 5.0f;        // ï¿½Ú“ï¿½ï¿½ï¿½ï¿½x
    [SerializeField] private move_camera refCamera;  // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ì‰ï¿½]ï¿½ï¿½ï¿½Qï¿½Æ‚ï¿½ï¿½ï¿½p
    //[SerializeField] private float applySpeed = 0.2f; //ï¿½ï¿½]ï¿½ï¿½ï¿½x
    [SerializeField] private float buff; //ï¿½ï¿½ï¿½ï¿½ï¿½Eï¿½ï¿½ï¿½ï¿½ï¿½oï¿½t

    //ï¿½Mï¿½~ï¿½bï¿½Nï¿½n
    private bool hasJump = false; // ï¿½Mï¿½~ï¿½bï¿½Nï¿½æ“¾ï¿½Ï‚İ‚ï¿½
    private float jumpPower = 5.0f;
    private Rigidbody rb;
    private bool isGrounded = false; // ï¿½ï¿½ ï¿½Ú’nï¿½tï¿½ï¿½ï¿½Oï¿½Ç‰ï¿½

    

    private Quaternion hRotation;
    private Vector3 pastG;
    private bool warp_flag;

    void Start()
    {
        hRotation = Quaternion.identity;
        rb = GetComponent<Rigidbody>();
        //ï¿½Åï¿½ï¿½Ìdï¿½Í•ï¿½ï¿½ï¿½ï¿½Ìæ“¾
        warp wp = GetComponent<warp>();
        pastG = wp.gravityDirection / 9.81f;
    }

    void Update()
    {
        //ï¿½ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½
        velocity = Vector3.zero;

        warp wp = GetComponent<warp>();
        Vector3 curG = wp.gravityDirection / 9.81f;
        //ï¿½dï¿½Í•ï¿½ï¿½ï¿½ï¿½ÆC WASDï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½Aï¿½ï¿½ï¿½ï¿½ï¿½È’nï¿½Ê‚ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½(velocity)ï¿½ğ“¾‚ï¿½
        if (curG == Vector3.down) //Maze1
        {
            if (Input.GetKey(KeyCode.W) || Input.GetKey("up"))
                velocity.z -= 1 * buff;
            if (Input.GetKey(KeyCode.A) || Input.GetKey("left"))
                velocity.x += 1 * buff;
            if (Input.GetKey(KeyCode.S) || Input.GetKey("down"))
                velocity.z += 1 * buff;
            if (Input.GetKey(KeyCode.D) || Input.GetKey("right"))
                velocity.x -= 1 * buff;

            refCamera.hRotation *= Quaternion.Euler(0, refCamera.mx, 0);
        }
        else if (curG == Vector3.right) //Maze2
        {
            if (Input.GetKey(KeyCode.W) || Input.GetKey("up"))
                velocity.y += 1 * buff;
            if (Input.GetKey(KeyCode.A) || Input.GetKey("left"))
                velocity.z += 1 * buff;
            if (Input.GetKey(KeyCode.S) || Input.GetKey("down"))
                velocity.y -= 1 * buff;
            if (Input.GetKey(KeyCode.D) || Input.GetKey("right"))
                velocity.z -= 1 * buff;

            refCamera.hRotation *= Quaternion.Euler(-refCamera.mx, 0, 0);
        }
        else if (curG == Vector3.up) //Maze3
        {
            if (Input.GetKey(KeyCode.W) || Input.GetKey("up"))
                velocity.z += 1 * buff;
            if (Input.GetKey(KeyCode.A) || Input.GetKey("left"))
                velocity.x += 1 * buff;
            if (Input.GetKey(KeyCode.S) || Input.GetKey("down"))
                velocity.z -= 1 * buff;
            if (Input.GetKey(KeyCode.D) || Input.GetKey("right"))
                velocity.x -= 1 * buff;

            refCamera.hRotation *= Quaternion.Euler(0, -refCamera.mx, 0);
        }
        else if (curG == Vector3.left) //Maze4
        {
            if (Input.GetKey(KeyCode.W) || Input.GetKey("up"))
                velocity.y += 1 * buff;
            if (Input.GetKey(KeyCode.A) || Input.GetKey("left"))
                velocity.z -= 1 * buff;
            if (Input.GetKey(KeyCode.S) || Input.GetKey("down"))
                velocity.y -= 1 * buff;
            if (Input.GetKey(KeyCode.D) || Input.GetKey("right"))
                velocity.z += 1 * buff;

            refCamera.hRotation *= Quaternion.Euler(refCamera.mx, 0, 0);
        }
        else if (curG == Vector3.forward) //Maze5
        {
            if (Input.GetKey(KeyCode.W) || Input.GetKey("up"))
                velocity.y += 1 * buff;
            if (Input.GetKey(KeyCode.A) || Input.GetKey("left"))
                velocity.x -= 1 * buff;
            if (Input.GetKey(KeyCode.S) || Input.GetKey("down"))
                velocity.y -= 1 * buff;
            if (Input.GetKey(KeyCode.D) || Input.GetKey("right"))
                velocity.x += 1 * buff;

            refCamera.hRotation *= Quaternion.Euler(0, 0, -refCamera.mx);
        }
        else if (curG == Vector3.back) //Maze6
        {
            if (Input.GetKey(KeyCode.W) || Input.GetKey("up"))
                velocity.y += 1 * buff;
            if (Input.GetKey(KeyCode.A) || Input.GetKey("left"))
                velocity.x += 1 * buff;
            if (Input.GetKey(KeyCode.S) || Input.GetKey("down"))
                velocity.y -= 1 * buff;
            if (Input.GetKey(KeyCode.D) || Input.GetKey("right"))
                velocity.x -= 1 * buff;

            refCamera.hRotation *= Quaternion.Euler(0, 0, refCamera.mx);
        }

        // ï¿½ï¿½ï¿½xï¿½xï¿½Nï¿½gï¿½ï¿½ï¿½Ì’ï¿½ï¿½ï¿½ï¿½ï¿½1ï¿½bï¿½ï¿½moveSpeedï¿½ï¿½ï¿½ï¿½ï¿½iï¿½Ş‚æ‚¤ï¿½É’ï¿½ï¿½ï¿½
        velocity = velocity.normalized * moveSpeed * Time.deltaTime;

       
        
        // ï¿½ï¿½ï¿½ï¿½ï¿½ê‚©ï¿½Ì•ï¿½ï¿½ï¿½ï¿½ÉˆÚ“ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ê‡
        if (velocity.magnitude > 0)
        {
            // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½Ì‰ï¿½](transform.rotation)ï¿½ÌXï¿½V
            // ï¿½ï¿½ï¿½ï¿½]ï¿½ï¿½Ô‚Ìƒvï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ï¿½Z+ï¿½ï¿½ï¿½ï¿½(ï¿½ã“ªï¿½ï¿½)ï¿½ï¿½ï¿½A
            // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½](refCamera.hRotation)ï¿½Å‰ñ‚µ‚ï¿½ï¿½Ú“ï¿½ï¿½Ì”ï¿½ï¿½Î•ï¿½ï¿½ï¿½(-velocity)ï¿½É‰ñ‚·‰ï¿½]ï¿½É’iï¿½Xï¿½ß‚Ã‚ï¿½ï¿½ï¿½
            //transform.rotation = Quaternion.Slerp(transform.rotation,
            //                                       Quaternion.LookRotation(hRotation * -velocity),
            //                                       applySpeed);

            transform.rotation = Quaternion.LookRotation(refCamera.hRotation * velocity);
        }

        // ï¿½vï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½[ï¿½ÌˆÊ’u(transform.position)ï¿½ÌXï¿½V
        // ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½](refCamera.hRotation)ï¿½Å‰ñ‚µ‚ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½(velocity)ï¿½ğ‘«‚ï¿½ï¿½ï¿½ï¿½ï¿½
        transform.position += refCamera.hRotation * velocity;

        pastG = curG;

        if (hasJump && isGrounded && Input.GetKeyDown(KeyCode.Space))
        {
            rb.AddForce(Vector3.up * jumpPower, ForceMode.Impulse);
        }
    }

    // ï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½ï¿½ï¿½vï¿½tï¿½^ï¿½iï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Î‚ï¿½ï¿½j
    public void Jump()
    {
        if (!hasJump)
        {
            hasJump = true;
            GetComponent<Renderer>().material.color = Color.red;
            rb.constraints = RigidbodyConstraints.FreezeRotation;
            StartCoroutine(JumpTimeLimit(10f));
        }
    }

    private IEnumerator JumpTimeLimit(float duration)
    {
        yield return new WaitForSeconds(duration);
        hasJump = false;
        GetComponent<Renderer>().material.color = Color.white;
    }

    // ï¿½ï¿½ ï¿½Ú’nï¿½ï¿½ï¿½ï¿½iï¿½nï¿½Ê‚Æ‚ÌÚGï¿½ï¿½ï¿½mï¿½Fï¿½j
    void OnCollisionStay(Collision collision)
    {
        // ï¿½nï¿½Ê‚ÆÚGï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½ï¿½ï¿½trueï¿½iLayerï¿½ï¿½^ï¿½Oï¿½Åiï¿½ï¿½ï¿½Ä‚ï¿½OKï¿½j
        isGrounded = true;
    }

    void OnCollisionExit(Collision collision)
    {
        isGrounded = false;
    }

    // ï¿½ï¿½ï¿½^ï¿½Cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½Oï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚Î‚ï¿½ï¿½j
    public void AddTime(float timeDelta)
    {
        GetComponent<Renderer>().material.color = Color.blue;
        time_attack ta = FindObjectOfType<time_attack>();
        if (ta != null)
        {
            ta.AddTimeFromItem(timeDelta);
        }
    }

    public void Speed(float multiplier, float duration)
    {
        StartCoroutine(SpeedBuff(multiplier, duration));
    }

    private IEnumerator SpeedBuff(float multiplier, float duration)
    {
        float originalSpeed = moveSpeed;
        moveSpeed *= multiplier;
        GetComponent<Renderer>().material.color = Color.gray; // ï¿½Fï¿½Åƒoï¿½tï¿½ï¿½\ï¿½ï¿½
        yield return new WaitForSeconds(duration);
        moveSpeed = originalSpeed;
        GetComponent<Renderer>().material.color = Color.white;
    }

    public void Reduce(float factor, float duration)
    {
        StartCoroutine(SpeedDebuffRoutine(factor, duration));
    }

    private IEnumerator SpeedDebuffRoutine(float factor, float duration)
    {
        float originalSpeed = moveSpeed;
        moveSpeed *= factor; // ï¿½ï¿½: factor = 0.5f ï¿½Å”ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½xï¿½ï¿½
        GetComponent<Renderer>().material.color = Color.cyan; // ï¿½Fï¿½ğ…Fï¿½ï¿½
        yield return new WaitForSeconds(duration);
        moveSpeed = originalSpeed;
        GetComponent<Renderer>().material.color = Color.white; // ï¿½ï¿½ï¿½ÌFï¿½É–ß‚ï¿½
    }

    

}

